<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@813.vb_d7c3d2984a_0">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2659.v52d3de6044d0">
    <parentIds>
      <string>42</string>
    </parentIds>
    <id>43</id>
    <startId>3</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1138.v619fd5201b_2f">
      <startTime>1645837317207</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1138.v619fd5201b_2f">
      <error class="hudson.AbortException">
        <detailMessage>docker login failed</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.docker.commons.impl.RegistryKeyMaterialFactory.materialize(RegistryKeyMaterialFactory.java:102)</trace>
          <trace>org.jenkinsci.plugins.docker.workflow.AbstractEndpointStepExecution2.doStart(AbstractEndpointStepExecution2.java:53)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.GeneralNonBlockingStepExecution.lambda$run$0(GeneralNonBlockingStepExecution.java:77)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:834)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
    <wf.a.ErrorAction plugin="workflow-api@1138.v619fd5201b_2f">
      <error class="hudson.AbortException" reference="../../wf.a.ErrorAction/error"/>
    </wf.a.ErrorAction>
  </actions>
</Tag>